build:
    environment:
        php:
            version: "7.0.9"

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - test/*

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
