name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install Dependancies
        run: composer install

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --verbose --dry-run

      - name: PHPUnit
        run: ./vendor/bin/phpunit
