name: CI

on:
  - push
  - pull_request

jobs:
  backwards-compatility:
    name: Backwards Compatibility

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: json
          tools: composer

      - name: Setup Backwards Compatibility Checker
        run: composer global require roave/backward-compatibility-check

      - name: Check Backwards Compatibility
        run: ~/.composer/vendor/bin/roave-backward-compatibility-check --from=0.1.0

  type-checking:
    name: Type Checking

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: json
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse

  coding-style:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: json
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --diff-format=udiff --dry-run --using-cache=false --verbose

  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']
        dependencies: ['lowest', 'highest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          tools: composer

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: Install Lowest Dependencies
        if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-suggest --prefer-lowest

      - name: Install Lowest Dependencies
        if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-suggest

      - name: PHPUnit
        run: ./vendor/bin/phpunit
