name: CI

on:
  - push
  - pull_request

jobs:
  backwards-compatility:
    name: Backwards Compatibility

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          tools: composer

      - name: Setup Backwards Compatibility Checker
        run: composer install -g roave/backward-compatibility-check

      - name: Check Backwards Compatibility
        run: roave-backward-compatibility-check --from=0.1.0

  type-checking:
    name: Type Checking

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          tools: composer

      - name: Install Dependancies
        run: composer install

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse

  coding-style:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          tools: composer

      - name: Install Dependancies
        run: composer install

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --diff-format=udiff --dry-run --using-cache=false --verbose

  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']
        deps: ['lowest', 'highest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          tools: composer

      - name: Install Lowest Dependancies
        if: matrix.deps == 'lowest'
        run: composer update --no-interaction --no-suggest --prefer-lowest

      - name: Install Lowest Dependancies
        if: matrix.deps == 'highest'
        run: composer update --no-interaction --no-suggest

      - name: PHPUnit
        run: ./vendor/bin/phpunit
